canopyConfig = {'isOrdered': False,
                'name': 'CANOPY',
                'partitionInputKind': [],
                'orderByColumn': '',
                'partitionAttributes': '',
                'unaliased_inputs': {'count': 0.0,
                                     'values': [],
                                     'desc': {}},
                'arguments': [{'datatype': 'DRIVER',
                               'isRequired': False,
                               'allowsLists': False,
                               'name': 'DOMAIN',
                               'value': ''},
                              {'datatype': 'DRIVER',
                               'isRequired': False,
                               'allowsLists': False,
                               'name': 'DATABASE',
                               'value': ''},
                              {'datatype': 'DRIVER',
                               'isRequired': False,
                               'allowsLists': False,
                               'name': 'USERID',
                               'value': ''},
                              {'datatype': 'DRIVER',
                               'isRequired': False,
                               'allowsLists': False,
                               'name': 'PASSWORD',
                               'value': ''},
                              {'datatype': 'DRIVER',
                               'isRequired': False,
                               'allowsLists': False,
                               'name': 'SSLSETTINGS',
                               'value': ''},
                              {'datatype': 'DRIVER',
                               'isRequired': False,
                               'allowsLists': False,
                               'name': 'SSLTRUSTSTOREPASSWORD',
                               'value': ''},
                              {'datatype': 'TABLE_NAME',
                               'isRequired': True,
                               'allowsLists': False,
                               'name': 'INPUTTABLE',
                               'value': 'computers_train1_public'},
                              {'datatype': 'DOUBLE',
                               'isRequired': True,
                               'allowsLists': False,
                               'name': 'LOOSEDISTANCE',
                               'value': '1000'},
                              {'datatype': 'DOUBLE',
                               'isRequired': True,
                               'allowsLists': False,
                               'name': 'TIGHTDISTANCE',
                               'value': '500'}],
                'required_input': [],
                'hasInputTable': False,
                'asterarguments': [{'name': 'schema',
                                    'value': '',
                                    'label': 'Schema'},
                                   {'name': 'outputType',
                                    'value': '',
                                    'label': 'Output Table Type'},
                                   {'name': 'hashKey',
                                    'value': '',
                                    'label': 'Hash Key Column'}]}

kmeansplotConfig = {'isOrdered': False,
                    'name': 'KMEANSPLOT',
                    'partitionInputKind': ['PartitionByAny'],
                    'orderByColumn': '',
                    'partitionAttributes': '',
                    'unaliased_inputs': {'count': 1.0,
                                         'values': ['computers_train1'],
                                         'desc': {}},
                    'arguments': [{'datatype': 'STRING',
                                   'isRequired': False,
                                   'allowsLists': False,
                                   'name': 'CENTROIDSTABLE',
                                   'value': 'dss.kmeanssample_centroid'},
                                  {'datatype': 'BOOLEAN',
                                   'isRequired': False,
                                   'allowsLists': False,
                                   'name': 'PRINTDISTANCE', 'value': False}],
                    'required_input': [{'kind': 'Dimension',
                                        'name': 'Dimension',
                                        'isOrdered': False,
                                        'value': 'kmeanssample',
                                        'orderByColumn': '',
                                        'isRequired': True,
                                        'partitionAttributes': ''}],
                    'hasInputTable': True,
                    'asterarguments': [{
                        'name': 'schema',
                        'value': '',
                        'label': 'Schema'},
                                       {'name': 'outputType',
                                        'value': '',
                                        'label': 'Output Table Type'},
                                       {'name': 'hashKey', 'value': '', 'label': 'Hash Key Column'}]}
