
npathConfig = {'isOrdered': True,
               'name': 'NPATH',
               'partitionInputKind': ['PartitionByKey'],
               'orderByColumn': 'ts',
               'partitionAttributes': ['id'],
               'unaliased_inputs': {'count': 1.0,
                                    'values': ['tv_shows'],
                                    'desc': {}},
               'arguments': [{'datatype': 'STRING',
                              'isRequired': True,
                              'allowsLists': False,
                              'name': 'MODE',
                              'value': 'nonoverlapping'},
                             {'datatype': 'STRING',
                              'isRequired': True,
                              'allowsLists': True,
                              'name': 'PATTERN',
                              'value': 'S1{1,3}.S2'},
                             {'datatype': 'SQLEXPR',
                              'isRequired': True,
                              'allowsLists': True,
                              'name': 'SYMBOLS',
                              'value': "tvshow='BreakingBad' as S2\x00tvshow <> 'BreakingBad' as S1"},
                             {'datatype': 'SQLEXPR',
                              'isRequired': True,
                              'allowsLists': True,
                              'name': 'RESULT',
                              'value': 'accumulate(tvshow of any(S1,S2)) as path'}],
               'required_input': [],
               'hasInputTable': True,
               'asterarguments': [{'name': 'schema',
                                   'value': '',
                                   'label': 'Schema'},
                                  {'name': 'outputType',
                                   'value': '',
                                   'label': 'Output Table Type'},
                                  {'name': 'hashKey',
                                   'value': '',
                                   'label': 'Hash Key Column'}]}