# -*- coding: utf-8 -*-
'''
Copyright © 2018 by Teradata.
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
associated documentation files (the "Software"), to deal in the Software without restriction,
including without limitation the rights to use, copy, modify, merge, publish, distribute,
sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
'''

'''
Created on May 15, 2017

@author: dt186022
'''

attributionMultiVersionConfig = {"orderByColumn":"time_stamp",
                         "partitionAttributes":["user_id"],
                         "unaliased_inputs":{"count":2,"values":["attribution_sample_table1", "attribution_sample_table2"],"desc":{}},
                         "name":"ATTRIBUTION",
                         "partitionInputKind":["PartitionByKey"],
                         "hasInputTable":True,
                         "asterarguments":[{"name":"schema","value":"","label":"Schema"},
                                           {"name":"outputType","value":"","label":"Output Table Type"},
                                           {"name":"hashKey","value":"","label":"Hash Key Column"}],
                         "required_input":[
                             {"kind":"Dimension",
                              "name":"conversion",
                              "isOrdered":False,
                              "value":"conversion_event_table",
                              "orderByColumn":"",
                              "isRequired":True,
                              "partitionAttributes":""},
                              {"kind":"Dimension",
                               "name":"excluding",
                               "isOrdered":False,
                               "value":"excluding_event_table",
                               "orderByColumn":"",
                               "isRequired":False,
                               "partitionAttributes":""},
                              {"kind":"Dimension",
                               "name":"optional",
                               "isOrdered":False,
                               "value":"optional_event_table",
                               "orderByColumn":"",
                               "isRequired":False,
                               "partitionAttributes":""},
                              {"kind":"Dimension",
                               "name":"model1",
                               "isOrdered":False,
                               "value":"model1_table",
                               "orderByColumn":"",
                               "isRequired":True,
                               "partitionAttributes":""},
                              {"kind":"Dimension",
                               "name":"model2",
                               "isOrdered":False,
                               "value":"model2_table",
                               "orderByColumn":"",
                               "isRequired":False,
                               "partitionAttributes":""}],
                         "isOrdered":True,
                         "arguments":[
                             {"datatype":"COLUMNS",
                              "isRequired":True,
                              "allowsLists":False,
                              "name":"EVENT_COLUMN_NAME",
                              "value":"event"},
                             {"datatype":"COLUMNS",
                              "isRequired":True,
                              "allowsLists":False,
                              "name":"TIMESTAMP_COLUMN_NAME",
                              "value":"time_stamp"},
                             {"datatype":"STRING",
                              "isRequired":False,
                              "allowsLists":True,
                              "name":"CONVERSION_EVENT_TYPE_VALUE",
                              "value":""},
                             {"datatype":"STRING",
                              "isRequired":False,
                              "allowsLists":True,
                              "name":"EXCLUDING_EVENT_TYPE_VALUE",
                              "value":""},
                             {"datatype":"STRING",
                              "isRequired":False,
                              "allowsLists":True,
                              "name":"OPTIONAL_EVENT_TYPE_VALUE",
                              "value":""},
                             {"datatype":"STRING",
                              "isRequired":True,
                              "allowsLists":False,
                              "name":"WINDOW",
                              "value":"rows:10&seconds:20"},
                             {"datatype":"STRING",
                              "isRequired":False,
                              "allowsLists":True,
                              "name":"MODEL1",
                              "value":""},
                             {"datatype":"STRING",
                              "isRequired":False,
                              "allowsLists":True,
                              "name":"MODEL2",
                              "value":""}]
                         }

textAttributionConfig = {"orderByColumn":"ts",
                         "partitionAttributes":["id"],
                         "unaliased_inputs":{"count":2,"values":["tv_shows"],"desc":{}},
                         "name":"ATTRIBUTION",
                         "partitionInputKind":["PartitionByKey"],
                         "hasInputTable":True,
                         "asterarguments":[{"name":"schema","value":"","label":"Schema"},
                                           {"name":"outputType","value":"","label":"Output Table Type"},
                                           {"name":"hashKey","value":"","label":"Hash Key Column"}],
                         "required_input":[
                             {"kind":"Dimension",
                              "name":"conversion",
                              "isOrdered":False,
                              "value":"",
                              "orderByColumn":"",
                              "isRequired":True,
                              "partitionAttributes":""},
                              {"kind":"Dimension",
                               "name":"excluding",
                               "isOrdered":False,
                               "value":"",
                               "orderByColumn":"",
                               "isRequired":False,
                               "partitionAttributes":""},
                              {"kind":"Dimension",
                               "name":"optional",
                               "isOrdered":False,
                               "value":"",
                               "orderByColumn":"",
                               "isRequired":False,
                               "partitionAttributes":""},
                              {"kind":"Dimension",
                               "name":"model1",
                               "isOrdered":False,
                               "value":"",
                               "orderByColumn":"",
                               "isRequired":True,
                               "partitionAttributes":""},
                              {"kind":"Dimension",
                               "name":"model2",
                               "isOrdered":False,
                               "value":"",
                               "orderByColumn":"",
                               "isRequired":False,
                               "partitionAttributes":""}],
                         "isOrdered":True,
                         "arguments":[
                             {"datatype":"COLUMNS",
                              "isRequired":True,
                              "allowsLists":False,
                              "name":"EVENT_COLUMN_NAME",
                              "value":"tvshow"},
                             {"datatype":"COLUMNS",
                              "isRequired":True,
                              "allowsLists":False,
                              "name":"TIMESTAMP_COLUMN_NAME",
                              "value":"ts"},
                             {"datatype":"STRING",
                              "isRequired":False,
                              "allowsLists":True,
                              "name":"CONVERSION_EVENT_TYPE_VALUE",
                              "value":"BreakingBad"},
                             {"datatype":"STRING",
                              "isRequired":False,
                              "allowsLists":True,
                              "name":"EXCLUDING_EVENT_TYPE_VALUE",
                              "value":""},
                             {"datatype":"STRING",
                              "isRequired":False,
                              "allowsLists":True,
                              "name":"OPTIONAL_EVENT_TYPE_VALUE",
                              "value":""},
                             {"datatype":"STRING",
                              "isRequired":True,
                              "allowsLists":False,
                              "name":"WINDOW",
                              "value":"seconds:1200"},
                             {"datatype":"STRING",
                              "isRequired":False,
                              "allowsLists":True,
                              "name":"MODEL1",
                              "value":"simple,uniform:na"},
                             {"datatype":"STRING",
                              "isRequired":False,
                              "allowsLists":True,
                              "name":"MODEL2",
                              "value":""}]
                         }

